routes/web.php
<?php

Route::get('view_sinh_vien_import','SinhVienController@view_sinh_vien_import')->name('import');
Route::post('process_sinh_vien_import','SinhVienController@process_sinh_vien_import')->name('process_sinh_vien_import');


Route::get('view_login','Controller@view_login')->name('view_login');
Route::get('logout','Controller@logout')->name('logout');
Route::post('process_login','Controller@process_login')->name('process_login');

Route::group([ 'middleware' => [ 'CheckLogin' ] ], function () {
Route::get('/','Controller@master')->name('home');
Route::get('profile','Controller@profile')->name('profile');
Route::get('update_profile','Controller@update_profile')->name('update_profile');
Route::post('process_update','Controller@process_update')->name('process_profile');
Route::group(['prefix' =>'khoa','as' => 'khoa.'],function(){
Route::get('','KhoaController@view_all')->name('view_all');
Route::get('view_insert','KhoaController@view_insert')->name('view_insert');
Route::post('process_insert','KhoaController@process_insert')->name('process_insert');
Route::get('view_update/{ma}','KhoaController@view_update')->name('view_update');
Route::post('process_update/{ma}','KhoaController@process_update')->name('process_update');
Route::get('delete/{ma}','KhoaController@delete')->name('delete');
});

Route::group(['middleware' => [ 'CheckGiaoVu' ],'prefix' =>'admin','as' => 'admin.'],function(){ 
Route::get('','AdminController@view_all')->name('view_all');
Route::get('view_insert','AdminController@view_insert')->name('view_insert');
Route::post('process_insert','AdminController@process_insert')->name('process_insert');
Route::get('view_update/{ma}','AdminController@view_update')->name('view_update');
Route::post('process_update/{ma}','AdminController@process_update')->name('process_update');
Route::get('delete/{ma}','AdminController@delete')->name('delete');
});

Route::group(['prefix' =>'lop','as' => 'lop.'],function(){ 
Route::get('','LopController@view_all')->name('view_all');
Route::get('view_insert','LopController@view_insert')->name('view_insert');
Route::post('process_insert','LopController@process_insert')->name('process_insert');
Route::get('view_update/{ma}','LopController@view_update')->name('view_update');
Route::post('process_update/{ma}','LopController@process_update')->name('process_update');
Route::get('delete/{ma}','LopController@delete')->name('delete');
});
Route::group(['prefix' =>'sinh_vien','as' => 'sinh_vien.'],function(){ 
Route::get('','SinhVienController@view_all')->name('view_all');
Route::get('view_insert','SinhVienController@view_insert')->name('view_insert');
Route::post('process_insert','SinhVienController@process_insert')->name('process_insert');
Route::get('view_update/{ma}','SinhVienController@view_update')->name('view_update');
Route::post('process_update/{ma}','SinhVienController@process_update')->name('process_update');
Route::get('delete/{ma}','SinhVienController@delete')->name('delete');
});

Route::group(['prefix' =>'cham_soc_sinh_vien','as' => 'cham_soc_sinh_vien.'],function(){ 
Route::get('','ChamSocSinhVienController@view_all')->name('view_all');
Route::get('view_insert','ChamSocSinhVienController@view_insert')->name('view_insert');
Route::post('process_insert','ChamSocSinhVienController@process_insert')->name('process_insert');
Route::get('view_update/{ma}','ChamSocSinhVienController@view_update')->name('view_update');
Route::post('process_update/{ma}','ChamSocSinhVienController@process_update')->name('process_update');
Route::get('delete/{ma}','ChamSocSinhVienController@delete')->name('delete');
});
Route::group(['prefix' =>'mon','as' => 'mon.'],function(){ 
Route::get('','MonController@view_all')->name('view_all');
Route::get('view_insert','MonController@view_insert')->name('view_insert');
Route::post('process_insert','MonController@process_insert')->name('process_insert');
Route::get('view_update/{ma}','MonController@view_update')->name('view_update');
Route::post('process_update/{ma}','MonController@process_update')->name('process_update');
Route::get('delete/{ma}','MonController@delete')->name('delete');
});
Route::group(['prefix' =>'phan_cong','as' => 'phan_cong.'],function(){ 
Route::get('','PhanCongController@view_all')->name('view_all');
Route::get('delete/{mon}/{admin}/{lop}','PhanCongController@delete')->name('delete');

Route::get('view_phan_cong','PhanCongController@view_phan_cong')->name('view_phan_cong');
Route::post('process_phan_cong','PhanCongController@process_phan_cong')->name('process_phan_cong');



});
Route::get('search','Controller@search')->name('search');
});

app/Models/PhanCong.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;


class PhanCong extends Model
{
	use Traits\HasCompositePrimaryKey;
	
    protected $table = 'phan_cong';
    public $timestamps = false;

    protected $fillable = ['ma_lop','ma_mon','ma_admin'];

    protected $primaryKey = ['ma_lop','ma_mon'];
    	public function admin()
{
	return $this->belongsTo('App\Models\Admin','ma_admin');
}
	public function mon()
{
	return $this->belongsTo('App\Models\Mon','ma_mon');
}
public function lop()
{
	return $this->belongsTo('App\Models\Lop','ma_lop');
}

}

app/Http/Controllers/PhanCongController.php
<?php

namespace App\Http\Controllers;
use Session;
use App\Models\Admin;
use App\Models\Mon;
use App\Models\Lop;
use App\Models\PhanCong;
use Illuminate\Http\Request;

class PhanCongController extends Controller
{
    public function view_all()
    {
       if(Session::get('cap_do')==0){
 $array_phan_cong = PhanCong::where('ma_admin',Session::get('ma'))->with('admin')->with('mon')->with('lop')->get();
      
        return view('phan_cong.view_all',compact('array_phan_cong'));
       }else{
         $array_phan_cong = PhanCong::with('admin')->with('mon')->with('lop')->get();
      // return  $array_phan_cong;
        return view('phan_cong.view_all',compact('array_phan_cong'));
       }

    }

    public function view_phan_cong()
    {
        $array_mon       = Mon::get();
        $array_giao_vien = Admin::where('cap_do',0)->get();
        $array_lop       = Lop::get();

        return view('phan_cong.view_phan_cong',compact('array_mon','array_giao_vien','array_lop'));
    }
    public function process_phan_cong(Request $rq)
    {
        PhanCong::updateOrCreate([
            'ma_lop' => $rq->ma_lop,
            'ma_mon' => $rq->ma_mon,
        ],[
            'ma_admin' => $rq->ma_giao_vien
        ]);
         return redirect()->route('phan_cong.view_all');
    }
    public function delete($mon,$admin,$lop)
    {
      PhanCong::where('ma_mon',$mon)->where('ma_admin',$admin)->where('ma_lop',$lop)->delete();
      return redirect()->route('phan_cong.view_all');
    }

}

resources/views/phan_cong/view_all.blade.php
@extends('layout.master')

@section('content')
<h1>
	Phân Công Giảng Dạy 
</h1>
@if(Session::get('cap_do')==1)
<a href="{{ route('phan_cong.view_phan_cong') }}" > thêm </a>
	@endif

<table class="table">
	<tr>
		<th>Môn</th>
		<th>Giáo Viên</th>
		<th>Lớp</th>
		@if(Session::get('cap_do')==1)
        <th>Xóa</th>
	@endif
		
	</tr>
	@foreach ($array_phan_cong as $phan_cong)
		<tr>
			<td>
				{{ $phan_cong->mon->ten }}
			</td>
			<td>
				{{ $phan_cong->admin->ten }}
			</td>
			<td>
				{{ $phan_cong->lop->ten }}
			</td>
			
			@if(Session::get('cap_do')==1)
<td><a href="{{ route('phan_cong.delete',['mon'=>$phan_cong->mon->ma,'admin'=>$phan_cong->admin->ma,'lop'=>$phan_cong->lop->ma,]) }}">Xóa</a></td>
	@endif
			
		</tr>
	@endforeach
</table>
@endsection

resources/views/phan_cong/view_all2.blade.php
@extends('layout.master')

@section('content')
<h1>
	Phân Công Giảng Dạy và Điểm Danh
</h1>

<table class="table">
	<tr>
		<th>Môn</th>
		<th>Giáo Viên</th>
		<th>Lớp</th>
		
	</tr>
	@foreach ($array_phan_cong as $phan_cong)
		<tr>
			<td>
				{{ $phan_cong->mon->ten }}
			</td>
			<td>
				{{ $phan_cong->admin->ten }}
			</td>
			<td>
				{{ $phan_cong->lop->ten }}
			</td>
			
			
		</tr>
	@endforeach
</table>
@endsection

resources/views/phan_cong/view_phan_cong.blade.php
@extends('layout.master')

@section('content')
<form action="{{ route('phan_cong.process_phan_cong') }}" method="post">
	{{ csrf_field() }}
	Chọn môn
	<select name="ma_mon">
		@foreach ($array_mon as $mon)
			<option value="{{ $mon->ma }}">
				{{ $mon->ten }}
			</option>
		@endforeach
	</select>
	<br>
	Chọn giáo viên
	<select name="ma_giao_vien">
		@foreach ($array_giao_vien as $giao_vien)
			<option value="{{ $giao_vien->ma }}">
				{{ $giao_vien->ten }}
			</option>
		@endforeach
	</select>
	<br>
	Chọn lớp
	<select name="ma_lop">
		@foreach ($array_lop as $lop)
			<option value="{{ $lop->ma }}">
				{{ $lop->ten }}
			</option>
		@endforeach
	</select>
	<br>
	<button>Phân công</button>
</form>

@endsection