routes/web.php
<?php

Route::get('view_sinh_vien_import','SinhVienController@view_sinh_vien_import')->name('import');
Route::post('process_sinh_vien_import','SinhVienController@process_sinh_vien_import')->name('process_sinh_vien_import');


Route::get('view_login','Controller@view_login')->name('view_login');
Route::get('logout','Controller@logout')->name('logout');
Route::post('process_login','Controller@process_login')->name('process_login');

Route::group([ 'middleware' => [ 'CheckLogin' ] ], function () {
Route::get('/','Controller@master')->name('home');
Route::get('profile','Controller@profile')->name('profile');
Route::get('update_profile','Controller@update_profile')->name('update_profile');
Route::post('process_update','Controller@process_update')->name('process_profile');
Route::group(['prefix' =>'khoa','as' => 'khoa.'],function(){
Route::get('','KhoaController@view_all')->name('view_all');
Route::get('view_insert','KhoaController@view_insert')->name('view_insert');
Route::post('process_insert','KhoaController@process_insert')->name('process_insert');
Route::get('view_update/{ma}','KhoaController@view_update')->name('view_update');
Route::post('process_update/{ma}','KhoaController@process_update')->name('process_update');
Route::get('delete/{ma}','KhoaController@delete')->name('delete');
});

Route::group(['middleware' => [ 'CheckGiaoVu' ],'prefix' =>'admin','as' => 'admin.'],function(){ 
Route::get('','AdminController@view_all')->name('view_all');
Route::get('view_insert','AdminController@view_insert')->name('view_insert');
Route::post('process_insert','AdminController@process_insert')->name('process_insert');
Route::get('view_update/{ma}','AdminController@view_update')->name('view_update');
Route::post('process_update/{ma}','AdminController@process_update')->name('process_update');
Route::get('delete/{ma}','AdminController@delete')->name('delete');
});

Route::group(['prefix' =>'lop','as' => 'lop.'],function(){ 
Route::get('','LopController@view_all')->name('view_all');
Route::get('view_insert','LopController@view_insert')->name('view_insert');
Route::post('process_insert','LopController@process_insert')->name('process_insert');
Route::get('view_update/{ma}','LopController@view_update')->name('view_update');
Route::post('process_update/{ma}','LopController@process_update')->name('process_update');
Route::get('delete/{ma}','LopController@delete')->name('delete');
});
Route::group(['prefix' =>'sinh_vien','as' => 'sinh_vien.'],function(){ 
Route::get('','SinhVienController@view_all')->name('view_all');
Route::get('view_insert','SinhVienController@view_insert')->name('view_insert');
Route::post('process_insert','SinhVienController@process_insert')->name('process_insert');
Route::get('view_update/{ma}','SinhVienController@view_update')->name('view_update');
Route::post('process_update/{ma}','SinhVienController@process_update')->name('process_update');
Route::get('delete/{ma}','SinhVienController@delete')->name('delete');
});

Route::group(['prefix' =>'cham_soc_sinh_vien','as' => 'cham_soc_sinh_vien.'],function(){ 
Route::get('','ChamSocSinhVienController@view_all')->name('view_all');
Route::get('view_insert','ChamSocSinhVienController@view_insert')->name('view_insert');
Route::post('process_insert','ChamSocSinhVienController@process_insert')->name('process_insert');
Route::get('view_update/{ma}','ChamSocSinhVienController@view_update')->name('view_update');
Route::post('process_update/{ma}','ChamSocSinhVienController@process_update')->name('process_update');
Route::get('delete/{ma}','ChamSocSinhVienController@delete')->name('delete');
});
Route::group(['prefix' =>'mon','as' => 'mon.'],function(){ 
Route::get('','MonController@view_all')->name('view_all');
Route::get('view_insert','MonController@view_insert')->name('view_insert');
Route::post('process_insert','MonController@process_insert')->name('process_insert');
Route::get('view_update/{ma}','MonController@view_update')->name('view_update');
Route::post('process_update/{ma}','MonController@process_update')->name('process_update');
Route::get('delete/{ma}','MonController@delete')->name('delete');
});
Route::group(['prefix' =>'phan_cong','as' => 'phan_cong.'],function(){ 
Route::get('','PhanCongController@view_all')->name('view_all');
Route::get('delete/{mon}/{admin}/{lop}','PhanCongController@delete')->name('delete');

Route::get('view_phan_cong','PhanCongController@view_phan_cong')->name('view_phan_cong');
Route::post('process_phan_cong','PhanCongController@process_phan_cong')->name('process_phan_cong');



});
Route::get('search','Controller@search')->name('search');
});

resources/views/layout/chat.blade.php
<div class="chat-window-wrapper">
        <div id="main-chat-wrapper" class="inner-content">
          <div class="chat-window-wrapper scroller scrollbar-dynamic" id="chat-users">
            <div class="chat-header">
              <div class="pull-left">
                <input type="text" placeholder="search">
              </div>
              <div class="pull-right">
                <a href="#" class="">
                  <div class="iconset top-settings-dark "></div>
                </a>
              </div>
            </div>
            <div class="side-widget">
              <div class="side-widget-title">group chats</div>
              <div class="side-widget-content">
                <div id="groups-list">
                  <ul class="groups">
                    <li>
                      <a href="#">
                        <div class="status-icon green"></div>Office work</a>
                    </li>
                    <li>
                      <a href="#">
                        <div class="status-icon green"></div>Personal vibes</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="side-widget fadeIn">
              <div class="side-widget-title">favourites</div>
              <div id="favourites-list">
                <div class="side-widget-content">
                  <div class="user-details-wrapper active" data-chat-status="online" data-chat-user-pic="assets/img/profiles/d.jpg" data-chat-user-pic-retina="assets/img/profiles/d2x.jpg" data-user-name="Jane Smith">
                    <div class="user-profile">
                      <img src="assets/img/profiles/d.jpg" alt="" data-src="assets/img/profiles/d.jpg" data-src-retina="assets/img/profiles/d2x.jpg" width="35" height="35">
                    </div>
                    <div class="user-details">
                      <div class="user-name">
                        Jane Smith
                      </div>
                      <div class="user-more">
                        Hello you there?
                      </div>
                    </div>
                    <div class="user-details-status-wrapper">
                      <span class="badge badge-important">3</span>
                    </div>
                    <div class="user-details-count-wrapper">
                      <div class="status-icon green"></div>
                    </div>
                    <div class="clearfix"></div>
                  </div>
                  <div class="user-details-wrapper" data-chat-status="busy" data-chat-user-pic="assets/img/profiles/d.jpg" data-chat-user-pic-retina="assets/img/profiles/d2x.jpg" data-user-name="David Nester">
                    <div class="user-profile">
                      <img src="assets/img/profiles/c.jpg" alt="" data-src="assets/img/profiles/c.jpg" data-src-retina="assets/img/profiles/c2x.jpg" width="35" height="35">
                    </div>
                    <div class="user-details">
                      <div class="user-name">
                        David Nester
                      </div>
                      <div class="user-more">
                        Busy, Do not disturb
                      </div>
                    </div>
                    <div class="user-details-status-wrapper">
                      <div class="clearfix"></div>
                    </div>
                    <div class="user-details-count-wrapper">
                      <div class="status-icon red"></div>
                    </div>
                    <div class="clearfix"></div>
                  </div>
                </div>
              </div>
            </div>
            <div class="side-widget">
              <div class="side-widget-title">more friends</div>
              <div class="side-widget-content" id="friends-list">
                <div class="user-details-wrapper" data-chat-status="online" data-chat-user-pic="assets/img/profiles/d.jpg" data-chat-user-pic-retina="assets/img/profiles/d2x.jpg" data-user-name="Jane Smith">
                  <div class="user-profile">
                    <img src="assets/img/profiles/d.jpg" alt="" data-src="assets/img/profiles/d.jpg" data-src-retina="assets/img/profiles/d2x.jpg" width="35" height="35">
                  </div>
                  <div class="user-details">
                    <div class="user-name">
                      Jane Smith
                    </div>
                    <div class="user-more">
                      Hello you there?
                    </div>
                  </div>
                  <div class="user-details-status-wrapper">
                  </div>
                  <div class="user-details-count-wrapper">
                    <div class="status-icon green"></div>
                  </div>
                  <div class="clearfix"></div>
                </div>
                <div class="user-details-wrapper" data-chat-status="busy" data-chat-user-pic="assets/img/profiles/d.jpg" data-chat-user-pic-retina="assets/img/profiles/d2x.jpg" data-user-name="David Nester">
                  <div class="user-profile">
                    <img src="assets/img/profiles/h.jpg" alt="" data-src="assets/img/profiles/h.jpg" data-src-retina="assets/img/profiles/h2x.jpg" width="35" height="35">
                  </div>
                  <div class="user-details">
                    <div class="user-name">
                      David Nester
                    </div>
                    <div class="user-more">
                      Busy, Do not disturb
                    </div>
                  </div>
                  <div class="user-details-status-wrapper">
                    <div class="clearfix"></div>
                  </div>
                  <div class="user-details-count-wrapper">
                    <div class="status-icon red"></div>
                  </div>
                  <div class="clearfix"></div>
                </div>
                <div class="user-details-wrapper" data-chat-status="online" data-chat-user-pic="assets/img/profiles/d.jpg" data-chat-user-pic-retina="assets/img/profiles/d2x.jpg" data-user-name="Jane Smith">
                  <div class="user-profile">
                    <img src="assets/img/profiles/c.jpg" alt="" data-src="assets/img/profiles/c.jpg" data-src-retina="assets/img/profiles/c2x.jpg" width="35" height="35">
                  </div>
                  <div class="user-details">
                    <div class="user-name">
                      Jane Smith
                    </div>
                    <div class="user-more">
                      Hello you there?
                    </div>
                  </div>
                  <div class="user-details-status-wrapper">
                  </div>
                  <div class="user-details-count-wrapper">
                    <div class="status-icon green"></div>
                  </div>
                  <div class="clearfix"></div>
                </div>
                <div class="user-details-wrapper" data-chat-status="busy" data-chat-user-pic="assets/img/profiles/d.jpg" data-chat-user-pic-retina="assets/img/profiles/d2x.jpg" data-user-name="David Nester">
                  <div class="user-profile">
                    <img src="assets/img/profiles/h.jpg" alt="" data-src="assets/img/profiles/h.jpg" data-src-retina="assets/img/profiles/h2x.jpg" width="35" height="35">
                  </div>
                  <div class="user-details">
                    <div class="user-name">
                      David Nester
                    </div>
                    <div class="user-more">
                      Busy, Do not disturb
                    </div>
                  </div>
                  <div class="user-details-status-wrapper">
                    <div class="clearfix"></div>
                  </div>
                  <div class="user-details-count-wrapper">
                    <div class="status-icon red"></div>
                  </div>
                  <div class="clearfix"></div>
                </div>
              </div>
            </div>
          </div>
          <div class="chat-window-wrapper" id="messages-wrapper" style="display:none">
            <div class="chat-header">
              <div class="pull-left">
                <input type="text" placeholder="search">
              </div>
              <div class="pull-right">
                <a href="#" class="">
                  <div class="iconset top-settings-dark "></div>
                </a>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="chat-messages-header">
              <div class="status online"></div><span class="semi-bold">Jane Smith(Typing..)</span>
              <a href="#" class="chat-back"><i class="icon-custom-cross"></i></a>
            </div>
            <div class="chat-messages scrollbar-dynamic clearfix">
              <div class="inner-scroll-content clearfix">
                <div class="sent_time">Yesterday 11:25pm</div>
                <div class="user-details-wrapper ">
                  <div class="user-profile">
                    <img src="assets/img/profiles/d.jpg" alt="" data-src="assets/img/profiles/d.jpg" data-src-retina="assets/img/profiles/d2x.jpg" width="35" height="35">
                  </div>
                  <div class="user-details">
                    <div class="bubble">
                      Hello, You there?
                    </div>
                  </div>
                  <div class="clearfix"></div>
                  <div class="sent_time off">Yesterday 11:25pm</div>
                </div>
                <div class="user-details-wrapper ">
                  <div class="user-profile">
                    <img src="assets/img/profiles/d.jpg" alt="" data-src="assets/img/profiles/d.jpg" data-src-retina="assets/img/profiles/d2x.jpg" width="35" height="35">
                  </div>
                  <div class="user-details">
                    <div class="bubble">
                      How was the meeting?
                    </div>
                  </div>
                  <div class="clearfix"></div>
                  <div class="sent_time off">Yesterday 11:25pm</div>
                </div>
                <div class="user-details-wrapper ">
                  <div class="user-profile">
                    <img src="assets/img/profiles/d.jpg" alt="" data-src="assets/img/profiles/d.jpg" data-src-retina="assets/img/profiles/d2x.jpg" width="35" height="35">
                  </div>
                  <div class="user-details">
                    <div class="bubble">
                      Let me know when you free
                    </div>
                  </div>
                  <div class="clearfix"></div>
                  <div class="sent_time off">Yesterday 11:25pm</div>
                </div>
                <div class="sent_time ">Today 11:25pm</div>
                <div class="user-details-wrapper pull-right">
                  <div class="user-details">
                    <div class="bubble sender">
                      Let me know when you free
                    </div>
                  </div>
                  <div class="clearfix"></div>
                  <div class="sent_time off">Sent On Tue, 2:45pm</div>
                </div>
              </div>
            </div>
            <div class="chat-input-wrapper" style="display:none">
              <textarea id="chat-message-input" rows="1" placeholder="Type your message"></textarea>
            </div>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>

resources/views/layout/header.blade.php
<div class="header navbar navbar-inverse ">
      <!-- BEGIN TOP NAVIGATION BAR -->
      <div class="navbar-inner">
        <div class="header-seperation">
          <ul class="nav pull-left notifcation-center visible-xs visible-sm">
            <li class="dropdown">
              <a href="#main-menu" data-webarch="toggle-left-side">
                <i class="material-icons">menu</i>
              </a>
            </li>
          </ul>
          <!-- BEGIN LOGO -->
          <a href="index.html">
            <img src="https://haymora.com/upload/images/cong_nghe_thong_tin/software/hoc_vien_cong_nghe_thong_tin_bach_khoa/bkacad-logo.jpg" class="logo" alt="" data-src="assets/img/logo.png" data-src-retina="assets/img/logo2x.png" width="110" height="40" />
          </a>
          <!-- END LOGO -->
          <ul class="nav pull-right notifcation-center">
            <li class="dropdown hidden-xs hidden-sm">
              <a href="index.html" class="dropdown-toggle active" data-toggle="">
                <i class="material-icons">home</i>
              </a>
            </li>
            <li class="dropdown hidden-xs hidden-sm">
              <a href="email.html" class="dropdown-toggle">
                <i class="material-icons">email</i><span class="badge bubble-only"></span>
              </a>
            </li>
            <li class="dropdown visible-xs visible-sm">
              <a href="#" data-webarch="toggle-right-side">
                <i class="material-icons">chat</i>
              </a>
            </li>
          </ul>
        </div>
        <!-- END RESPONSIVE MENU TOGGLER -->
        <div class="header-quick-nav">
          <!-- BEGIN TOP NAVIGATION MENU -->
          <div class="pull-left">
            <ul class="nav quick-section">
              <li class="quicklinks">
                <a href="#" class="" id="layout-condensed-toggle">
                  <i class="material-icons">menu</i>
                </a>
              </li>
            </ul>
            <ul class="nav quick-section">
              <li class="quicklinks  m-r-10">
                <a href="#" class="">
                  <i class="material-icons">refresh</i>
                </a>
              </li>
              <li class="quicklinks">
                <a href="#" class="">
                  <i class="material-icons">apps</i>
                </a>
              </li>
              <li class="quicklinks"> <span class="h-seperate"></span></li>
              <li class="quicklinks">
                <a href="#" class="" id="my-task-list" data-placement="bottom" data-content='' data-toggle="dropdown" data-original-title="Notifications">
                  <i class="material-icons">notifications_none</i>
                  <span class="badge badge-important bubble-only"></span>
                </a>
              </li>
              <li class="m-r-10 input-prepend inside search-form no-boarder">
                <form action="{{ route('search') }}" method="get">
                <span class="add-on"> <i class="material-icons">search</i></span>
                <input name="search" type="text" class="no-boarder " placeholder="Tìm kiếm Sinh Viên" style="width:250px;">
              </form>
              </li>
            </ul>
          </div>
          <div id="notification-list" style="display:none">
            <div style="width:300px">
              <div class="notification-messages info">
                <div class="user-profile">
                  <img src="assets/img/profiles/d.jpg" alt="" data-src="assets/img/profiles/d.jpg" data-src-retina="assets/img/profiles/d2x.jpg" width="35" height="35">
                </div>
                <div class="message-wrapper">
                  <div class="heading">
                    David Nester - Commented on your wall
                  </div>
                  <div class="description">
                    Meeting postponed to tomorrow
                  </div>
                  <div class="date pull-left">
                    A min ago
                  </div>
                </div>
                <div class="clearfix"></div>
              </div>
              <div class="notification-messages danger">
                <div class="iconholder">
                  <i class="icon-warning-sign"></i>
                </div>
                <div class="message-wrapper">
                  <div class="heading">
                    Server load limited
                  </div>
                  <div class="description">
                    Database server has reached its daily capicity
                  </div>
                  <div class="date pull-left">
                    2 mins ago
                  </div>
                </div>
                <div class="clearfix"></div>
              </div>
              <div class="notification-messages success">
                <div class="user-profile">
                  <img src="assets/img/profiles/h.jpg" alt="" data-src="assets/img/profiles/h.jpg" data-src-retina="assets/img/profiles/h2x.jpg" width="35" height="35">
                </div>
                <div class="message-wrapper">
                  <div class="heading">
                    You haveve got 150 messages
                  </div>
                  <div class="description">
                    150 newly unread messages in your inbox
                  </div>
                  <div class="date pull-left">
                    An hour ago
                  </div>
                </div>
                <div class="clearfix"></div>
              </div>
            </div>
          </div>
          <!-- END TOP NAVIGATION MENU -->
          <!-- BEGIN CHAT TOGGLER -->
          <div class="pull-right">
            <div class="chat-toggler sm">
              <div class="profile-pic">
                <img src="assets/img/profiles/avatar_small.jpg" alt="" data-src="assets/img/profiles/avatar_small.jpg" data-src-retina="assets/img/profiles/avatar_small2x.jpg" width="35" height="35" />
                <div class="availability-bubble online"></div>
              </div>
            </div>
            <ul class="nav quick-section ">
              <li class="quicklinks">
                <a data-toggle="dropdown" class="dropdown-toggle  pull-right " href="#" id="user-options">
                  <i class="material-icons">tune</i>
                </a>
                <ul class="dropdown-menu  pull-right" role="menu" aria-labelledby="user-options">
                  <li>
                    <a href="{{ route('profile') }}"><i class="material-icons">power_settings_new</i>&nbsp;&nbsp;Thông tin cá nhân</a>
                  </li>
                  <li>
                    <a href="{{ route('logout') }}"><i class="material-icons">power_settings_new</i>&nbsp;&nbsp;Log Out</a>
                  </li>
                </ul>
              </li>
              <li class="quicklinks"> <span class="h-seperate"></span></li>
              <li class="quicklinks">
                <a href="#" class="chat-menu-toggle" data-webarch="toggle-right-side"><i class="material-icons">chat</i><span class="badge badge-important hide">1</span>
        </a>
                <div class="simple-chat-popup chat-menu-toggle hide">
                  <div class="simple-chat-popup-arrow"></div>
                  <div class="simple-chat-popup-inner">
                    <div style="width:100px">
                      <div class="semi-bold">David Nester</div>
                      <div class="message">Hey you there </div>
                    </div>
                  </div>
                </div>
              </li>
            </ul>
          </div>
          <!-- END CHAT TOGGLER -->
        </div>
        <!-- END TOP NAVIGATION MENU -->
      </div>
      <!-- END TOP NAVIGATION BAR -->
    </div>

resources/views/layout/sidebar_menu_giao_vien.blade.php
<p class="menu-title sm">BROWSE <span class="pull-right"><a href="javascript:;"><i class="material-icons">refresh</i></a></span></p>
          <ul>
            <li class="start  open active "> <a href="{{ route('home') }}"><i class="material-icons">home</i> trang chủ  </a>

            </li>
           
            <li>
              <a href="{{ route('phan_cong.view_all') }}"> <i class="material-icons">flip</i> Phân công</a>

            </li>

resources/views/layout/sidebar_menu_giao_vu.blade.php
<p class="menu-title sm">BROWSE <span class="pull-right"><a href="javascript:;"><i class="material-icons">refresh</i></a></span></p>
          <ul>
            <li class="start  open active "> <a href="{{ route('home') }}"><i class="material-icons">home</i> trang chủ  </a>

            </li>
            <li>
              <a href="{{ route('khoa.view_all') }}"> <i class="material-icons">panorama_horizontal</i> <span class="title">QL Khóa</span> </a>
            </li>
            <li>
              <a href="{{ route('lop.view_all') }}"> <i class="material-icons">email</i> QL Lớp
              </a>
            </li>
            <li>
              <a href="{{ route('sinh_vien.view_all') }}"> <i class="material-icons">invert_colors</i>QL Sinh Viên  </a>

            </li>
            <li>
              <a href="{{ route('cham_soc_sinh_vien.view_all') }}"> <i class="material-icons">airplay</i> Chăm sóc sinh viên </a>

            </li>
            <li>
               @if (Session::get('cap_do')==1)
              <a href="{{ route('admin.view_all') }}"> <i class="material-icons">flip</i>QL Admin</a>
             @endif


            </li>
           
            <li>
              <a href="{{ route('mon.view_all') }}"> <i class="material-icons">view_stream</i> QL Môn </a>

            </li>
            <li>
              <a href="{{ route('phan_cong.view_all') }}"> <i class="material-icons">flip</i> QL Phân công</a>

            </li>