routes/web.php
<?php

Route::get('view_sinh_vien_import','SinhVienController@view_sinh_vien_import')->name('import');
Route::post('process_sinh_vien_import','SinhVienController@process_sinh_vien_import')->name('process_sinh_vien_import');


Route::get('view_login','Controller@view_login')->name('view_login');
Route::get('logout','Controller@logout')->name('logout');
Route::post('process_login','Controller@process_login')->name('process_login');

Route::group([ 'middleware' => [ 'CheckLogin' ] ], function () {
Route::get('/','Controller@master')->name('home');
Route::get('profile','Controller@profile')->name('profile');
Route::get('update_profile','Controller@update_profile')->name('update_profile');
Route::post('process_update','Controller@process_update')->name('process_profile');
Route::group(['prefix' =>'khoa','as' => 'khoa.'],function(){
Route::get('','KhoaController@view_all')->name('view_all');
Route::get('view_insert','KhoaController@view_insert')->name('view_insert');
Route::post('process_insert','KhoaController@process_insert')->name('process_insert');
Route::get('view_update/{ma}','KhoaController@view_update')->name('view_update');
Route::post('process_update/{ma}','KhoaController@process_update')->name('process_update');
Route::get('delete/{ma}','KhoaController@delete')->name('delete');
});

Route::group(['middleware' => [ 'CheckGiaoVu' ],'prefix' =>'admin','as' => 'admin.'],function(){ 
Route::get('','AdminController@view_all')->name('view_all');
Route::get('view_insert','AdminController@view_insert')->name('view_insert');
Route::post('process_insert','AdminController@process_insert')->name('process_insert');
Route::get('view_update/{ma}','AdminController@view_update')->name('view_update');
Route::post('process_update/{ma}','AdminController@process_update')->name('process_update');
Route::get('delete/{ma}','AdminController@delete')->name('delete');
});

Route::group(['prefix' =>'lop','as' => 'lop.'],function(){ 
Route::get('','LopController@view_all')->name('view_all');
Route::get('view_insert','LopController@view_insert')->name('view_insert');
Route::post('process_insert','LopController@process_insert')->name('process_insert');
Route::get('view_update/{ma}','LopController@view_update')->name('view_update');
Route::post('process_update/{ma}','LopController@process_update')->name('process_update');
Route::get('delete/{ma}','LopController@delete')->name('delete');
});
Route::group(['prefix' =>'sinh_vien','as' => 'sinh_vien.'],function(){ 
Route::get('','SinhVienController@view_all')->name('view_all');
Route::get('view_insert','SinhVienController@view_insert')->name('view_insert');
Route::post('process_insert','SinhVienController@process_insert')->name('process_insert');
Route::get('view_update/{ma}','SinhVienController@view_update')->name('view_update');
Route::post('process_update/{ma}','SinhVienController@process_update')->name('process_update');
Route::get('delete/{ma}','SinhVienController@delete')->name('delete');
});

Route::group(['prefix' =>'cham_soc_sinh_vien','as' => 'cham_soc_sinh_vien.'],function(){ 
Route::get('','ChamSocSinhVienController@view_all')->name('view_all');
Route::get('view_insert','ChamSocSinhVienController@view_insert')->name('view_insert');
Route::post('process_insert','ChamSocSinhVienController@process_insert')->name('process_insert');
Route::get('view_update/{ma}','ChamSocSinhVienController@view_update')->name('view_update');
Route::post('process_update/{ma}','ChamSocSinhVienController@process_update')->name('process_update');
Route::get('delete/{ma}','ChamSocSinhVienController@delete')->name('delete');
});
Route::group(['prefix' =>'mon','as' => 'mon.'],function(){ 
Route::get('','MonController@view_all')->name('view_all');
Route::get('view_insert','MonController@view_insert')->name('view_insert');
Route::post('process_insert','MonController@process_insert')->name('process_insert');
Route::get('view_update/{ma}','MonController@view_update')->name('view_update');
Route::post('process_update/{ma}','MonController@process_update')->name('process_update');
Route::get('delete/{ma}','MonController@delete')->name('delete');
});
Route::group(['prefix' =>'phan_cong','as' => 'phan_cong.'],function(){ 
Route::get('','PhanCongController@view_all')->name('view_all');
Route::get('delete/{mon}/{admin}/{lop}','PhanCongController@delete')->name('delete');

Route::get('view_phan_cong','PhanCongController@view_phan_cong')->name('view_phan_cong');
Route::post('process_phan_cong','PhanCongController@process_phan_cong')->name('process_phan_cong');



});
Route::get('search','Controller@search')->name('search');
});

resources/views/admin/view_all.blade.php
@extends('layout.master')

@section('content')
<h1>
	Quản Lý Admin
	
</h1>
<a href="{{ route('admin.view_insert') }}" > thêm </a> <table class="table">
	<tr>
		<th>mã</th>
		<th>Tên</th>
		<th>email</th>
		<th>cấp độ</th>
		
		<th>Xóa</th>
	</tr>
	@foreach ($array_admin as $admin)
		<tr>
			<td>
				{{ $admin->ma }}
			</td>
			<td>
				{{ $admin->ten}}
			</td>
			<td>
				{{ $admin->email}}

			</td>
			<td>
				@if ( $admin->cap_do==1)
					Giáo vụ
				@else
					Giáo viên
				@endif
			</td>
			
			@if ($admin->cap_do==0)
				<td>
				<a href="{{ route('admin.delete',['ma'=> $admin->ma]) }}">xóa</a>
			</td>
			@else
			<td></td>
			@endif
		</tr>
	@endforeach
</table>
@endsection

resources/views/admin/view_insert.blade.php
@extends('layout.master')

@section('content')

<form action="{{ route('admin.process_insert') }}" method="post">
	{{ csrf_field()}}
	tên
	<input type="text" name="ten">
	<br>
	email
	<input type="email" name="email">
	<br>
	pass
	<input type="passwork" name="mat_khau">
	<br>
	cấp độ
	<input type="radio" name="cap_do" value="1">Giáo Vụ
	<input type="radio" name="cap_do" value="0">Giáo Viên
	<br>
	<button>thêm</button>

</form> 

@endsection

resources/views/admin/view_update.blade.php
@extends('layout.master')

@section('content')
<form action="{{ route('admin.process_update',['ma' => $giao_vu->ma]) }}" method="post">
	{{ csrf_field()}}
	tên
	<input type="text" name="ten" value="{{ $giao_vu->ten}}"><br>
	email
	<input type="text" name="email" value="{{ $giao_vu->email}}"><br>
	mật khâu
	<input type="text" name="mat_khau" value="{{ $giao_vu->mat_khau}}">

	<button>sua</button>

</form> 
@endsection