routes/web.php
<?php

Route::get('view_sinh_vien_import','SinhVienController@view_sinh_vien_import')->name('import');
Route::post('process_sinh_vien_import','SinhVienController@process_sinh_vien_import')->name('process_sinh_vien_import');


Route::get('view_login','Controller@view_login')->name('view_login');
Route::get('logout','Controller@logout')->name('logout');
Route::post('process_login','Controller@process_login')->name('process_login');

Route::group([ 'middleware' => [ 'CheckLogin' ] ], function () {
Route::get('/','Controller@master')->name('home');
Route::get('profile','Controller@profile')->name('profile');
Route::get('update_profile','Controller@update_profile')->name('update_profile');
Route::post('process_update','Controller@process_update')->name('process_profile');
Route::group(['prefix' =>'khoa','as' => 'khoa.'],function(){
Route::get('','KhoaController@view_all')->name('view_all');
Route::get('view_insert','KhoaController@view_insert')->name('view_insert');
Route::post('process_insert','KhoaController@process_insert')->name('process_insert');
Route::get('view_update/{ma}','KhoaController@view_update')->name('view_update');
Route::post('process_update/{ma}','KhoaController@process_update')->name('process_update');
Route::get('delete/{ma}','KhoaController@delete')->name('delete');
});

Route::group(['middleware' => [ 'CheckGiaoVu' ],'prefix' =>'admin','as' => 'admin.'],function(){ 
Route::get('','AdminController@view_all')->name('view_all');
Route::get('view_insert','AdminController@view_insert')->name('view_insert');
Route::post('process_insert','AdminController@process_insert')->name('process_insert');
Route::get('view_update/{ma}','AdminController@view_update')->name('view_update');
Route::post('process_update/{ma}','AdminController@process_update')->name('process_update');
Route::get('delete/{ma}','AdminController@delete')->name('delete');
});

Route::group(['prefix' =>'lop','as' => 'lop.'],function(){ 
Route::get('','LopController@view_all')->name('view_all');
Route::get('view_insert','LopController@view_insert')->name('view_insert');
Route::post('process_insert','LopController@process_insert')->name('process_insert');
Route::get('view_update/{ma}','LopController@view_update')->name('view_update');
Route::post('process_update/{ma}','LopController@process_update')->name('process_update');
Route::get('delete/{ma}','LopController@delete')->name('delete');
});
Route::group(['prefix' =>'sinh_vien','as' => 'sinh_vien.'],function(){ 
Route::get('','SinhVienController@view_all')->name('view_all');
Route::get('view_insert','SinhVienController@view_insert')->name('view_insert');
Route::post('process_insert','SinhVienController@process_insert')->name('process_insert');
Route::get('view_update/{ma}','SinhVienController@view_update')->name('view_update');
Route::post('process_update/{ma}','SinhVienController@process_update')->name('process_update');
Route::get('delete/{ma}','SinhVienController@delete')->name('delete');
});

Route::group(['prefix' =>'cham_soc_sinh_vien','as' => 'cham_soc_sinh_vien.'],function(){ 
Route::get('','ChamSocSinhVienController@view_all')->name('view_all');
Route::get('view_insert','ChamSocSinhVienController@view_insert')->name('view_insert');
Route::post('process_insert','ChamSocSinhVienController@process_insert')->name('process_insert');
Route::get('view_update/{ma}','ChamSocSinhVienController@view_update')->name('view_update');
Route::post('process_update/{ma}','ChamSocSinhVienController@process_update')->name('process_update');
Route::get('delete/{ma}','ChamSocSinhVienController@delete')->name('delete');
});
Route::group(['prefix' =>'mon','as' => 'mon.'],function(){ 
Route::get('','MonController@view_all')->name('view_all');
Route::get('view_insert','MonController@view_insert')->name('view_insert');
Route::post('process_insert','MonController@process_insert')->name('process_insert');
Route::get('view_update/{ma}','MonController@view_update')->name('view_update');
Route::post('process_update/{ma}','MonController@process_update')->name('process_update');
Route::get('delete/{ma}','MonController@delete')->name('delete');
});
Route::group(['prefix' =>'phan_cong','as' => 'phan_cong.'],function(){ 
Route::get('','PhanCongController@view_all')->name('view_all');
Route::get('delete/{mon}/{admin}/{lop}','PhanCongController@delete')->name('delete');

Route::get('view_phan_cong','PhanCongController@view_phan_cong')->name('view_phan_cong');
Route::post('process_phan_cong','PhanCongController@process_phan_cong')->name('process_phan_cong');



});
Route::get('search','Controller@search')->name('search');
});

app/Models/SinhVien.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class SinhVien extends Model
{
   protected $table = 'sinh_vien';
   protected $fillable = [
    	'ten',
    	'dia_chi',
        'ngay_sinh',
        'gioi_tinh',
        'email',
        'sdt',
        'sdt_phu_huynh',
        'ma_lop',

        
    	
    	
    ];
    public $timestamps = false;
    protected $primaryKey = 'ma';
            public function lop()
{
    return $this->belongsTo('App\Models\Lop','ma_lop');
}
public function getTenGioiTinhAttribute()
{
    if ($this->gioi_tinh) {
       return "Nam"  ;  
   } 
   else {
       return "Nữ";
    }
    
}

}

app/Http/Controllers/SinhVienController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\http\Request;
use App\Models\SinhVien;
use App\Models\Lop;
use Maatwebsite\Excel\Facades\Excel;
use App\Imports\SinhVienImport;

class SinhVienController extends BaseController
{
    public function view_all()
    {
    	$array_sinh_vien = SinhVien::with('lop')->get();
        
    	return view('sinh_vien.view_all',compact('array_sinh_vien'));
    }
    public function view_insert()
    {
        $array_lop = Lop::get();

    	return view('sinh_vien.view_insert',compact('array_lop'));
    }
    public function process_insert(Request $rq)
    {
    	SinhVien::create($rq->all());
    	return redirect()->route('sinh_vien.view_all');
    		
    }
    public function view_update($ma)
    {
        $array_lop = Lop::get();
    	$sinh_vien = SinhVien::where('ma','=',$ma)->first();

    //	$sinh_vien = SinhVien::find($ma);
    return view('sinh_vien.view_update', compact('sinh_vien','array_lop'));
    }
    public function process_update($ma, Request $rq)
    {
    	SinhVien::find($ma)->update($rq->all());
    	return redirect()->route('sinh_vien.view_all');
    }
    public function delete($ma)
    {
    	SinhVien::find($ma)->delete();
    	return redirect()->route('sinh_vien.view_all');
    }
    public function view_sinh_vien_import()
    {
        return view('sinh_vien.view_sinh_vien_import');
    }
    public function process_sinh_vien_import(Request $rq)
    {
            Excel::import(new SinhVienImport, $rq -> file_sinh_vien);
            return redirect()->route('sinh_vien.view_all');
    }

}

resources/views/sinh_vien/view_all.blade.php
@extends('layout.master')

@section('content')
<h1>
	Quản Lý Sinh Viên
</h1>
<a href="{{ route('sinh_vien.view_insert') }}" > thêm </a><br>
<a href="{{ route('import') }}">thêm nhiều</a>
<table class="table">
	<tr>
		<th>mã</th>
		<th>khóa</th>
		<th>Lớp</th>
		<th>Tên</th>
		<th>ngày sinh</th>
		<th>địa chỉ</th>
		<th>giới tính</th>
		<th>email</th>
		<th>SĐT</th>
		<th>SĐT phụ huynh</th>
		<th>Sửa</th>
		<th>Xóa</th>
		<th>Chăm Sóc</th>
		
	</tr>
	@foreach ($array_sinh_vien as $sinh_vien)
		<tr>
			<td>
				{{ $sinh_vien->ma }}
			</td>
			<td>
				{{ $sinh_vien->lop->khoa->ten }}
			</td>
			<td>
				{{ $sinh_vien->lop->ten }}
			</td>

			<td>


				{{ $sinh_vien->ten}}
			</td>
			<td>
				{{ $sinh_vien->ngay_sinh}}
			</td>
			<td>
				{{ $sinh_vien->dia_chi}}
			</td>
			<td>
				{{ $sinh_vien->ten_gioi_tinh}}
			</td>
			<td>
				{{ $sinh_vien->email}}
			</td>
			<td>
				{{ $sinh_vien->sdt}}
			</td>
			<td>
				{{ $sinh_vien->sdt_phu_huynh}}
			</td>
			<td>
				<a href="{{ route('sinh_vien.view_update',['ma'=> $sinh_vien->ma]) }}">Sửa</a>
			</td>
			<td>
				<a href="{{ route('sinh_vien.delete',['ma'=> $sinh_vien->ma]) }}">Xóa</a>
			</td>
			<td>
				<a href="{{ route('cham_soc_sinh_vien.view_insert',['ma_sinh_vien'=> $sinh_vien->ma]) }}" > Chăm Sóc </a>
			</td>
		</tr>
	@endforeach
</table>
@endsection

resources/views/sinh_vien/view_insert.blade.php
@extends('layout.master')

@section('content')

<form action="{{ route('sinh_vien.process_insert') }}" method="post">
	{{ csrf_field()}}
	<div>
	tên
	<input type="text" name="ten">
	<br>
	địa chỉ
	<input type="text" name="dia_chi">
	<br>
	ngày sinh
	<input type="date" name="ngay_sinh">
	<br>
	email
	<input type="text" name="email">
	<br>
	sdt
	<input type="number" name="sdt">
	<br>
	sdt phụ huynh
	<input type="number" name="sdt_phu_huynh">
	<br>
	
	giới tinh
	<input type="radio" name="gioi_tinh" value="1">Nam
	<input type="radio" name="gioi_tinh" value="0">Nữ
	<br>
	Lớp
		<select name="ma_lop" >
		@foreach ($array_lop as $lop)
			<option value="{{ $lop->ma}}">
				{{ $lop->ten}}
			</option>
			
		@endforeach
	</select>
	<br>
	<button>thêm</button>
</div>

</form> @endsection

resources/views/sinh_vien/view_sinh_vien_import.blade.php
@extends('layout.master')

@section('content')
<form action="{{ route('process_sinh_vien_import') }}" method="post" enctype="multipart/form-data">
	{{ csrf_field() }}
	Lấy file mấu nếu chưa có
	<a href="https://drive.google.com/file/d/1oBCzrPYMuHrZ0gUuC0XvHZ8gYGkoa-3Q/view?usp=sharing" >File Mẫu</a>(Lưu ý : Điền Đầy Đủ Thông Tin Giống Như file mẫu)<br>
	Chọn file Excel
	<input type="file" name="file_sinh_vien" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet">
	<button>Nhập vào</button>
</form>

@endsection

resources/views/sinh_vien/view_update.blade.php
@extends('layout.master')

@section('content')
<form action="{{ route('sinh_vien.process_update',['ma' => $sinh_vien->ma]) }}" method="post">
	{{ csrf_field()}}
	tên
	<input type="text" name="ten" value="{{ $sinh_vien->ten }}">
	<br>
	địa chỉ
	<input type="text" name="dia_chi" value="{{ $sinh_vien->dia_chi }}">
	<br>
	ngày sinh
	
	<input type="text" name="ngay_sinh" value="{{ $sinh_vien->ngay_sinh }}">
	<br>
	email
	<input type="text" name="email" value="{{ $sinh_vien->email }}">
	<br>
	sdt
	<input type="text" name="sdt" value="{{ $sinh_vien->sdt }}">
	<br>
	sdt phụ huynh
	<input type="text" name="sdt_phu_huynh" value="{{ $sinh_vien->sdt_phu_huynh }}">
	<br>
	
	giới tinh
	<input type="radio" name="gioi_tinh" value="1">Nam
	
	<input type="radio" name="gioi_tinh" value="0">Nữ
	
	
	<br>
	Lớp
		<select name="ma_lop" >
		@foreach ($array_lop as $lop)
			<option value="{{ $lop->ma}}">
				{{ $lop->ten}}
			</option>
			
		@endforeach
	</select>
	<button>sua</button>

</form> 
@endsection